### ISSUE TITLE
FileGenerator class

### ISSUE THREAD

**Issue by VanLaareN** [precice-forschungsprojekt/controller#10]
**Short description**
Class that generates content of the necessary files.

**Details**
Create a class, which generates the content of the neccessary files (like README.md, precice-config.xml etc).

**Subtasks**
- [x] Create a class
- [ ] Implement precice-config.xml generation
- [ ] Implement run.sh generation
- [ ] Implement clean.sh generation
- [ ] Implement README.md generation
- [ ] Implement adapter-config.json generation

**Dependencies**
This task depends on #6 to be finished
