### ISSUE TITLE
Generate file-folder structure

### ISSUE THREAD

**Issue by VanLaareN** [precice-forschungsprojekt/controller#6]
**Short description**
Generate File-Folder structure for the generated files

**Details**
Generate Files and palce them in the structure accodingly.

**Subtasks**
- [x] Schema: Create general schema of the structure, ie where the files are supposed to land.
- [x] Generate Files: Generate all of the necessary files (Dont have to be fully implemented, since this is only a general case).
- [x] Placement: Place the files in the structure and write out to disk.

**Dependencies**
This task has no dependecies.

**Comment by VanLaareN** [comment]
Issue is solved
